# Generated by Django 3.0.3 on 2020-03-19 22:09

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='music/media/images/noim.jpg', upload_to=music.models.image_directory_path),
        ),
    ]
