# Generated by Django 3.0.3 on 2020-03-19 23:21

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='music/media/images/noim.png', upload_to=music.models.image_directory_path),
        ),
    ]
