# Generated by Django 3.0.3 on 2020-03-26 00:21

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200325_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.image_directory_path),
        ),
    ]
